vich_uploader:
    db_driver: orm

    mappings:
       vehicles:
           uri_prefix: /images/vehicles
           upload_destination: '%kernel.project_dir%/public/images/vehicles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


