vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        vehicles:
            uri_prefix: /images/vehicles
            upload_destination: '%kernel.project_dir%/public/images/vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update : false


